// this is for writing the basic html text
const String page PROGMEM = "<head>"
                            " <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>"
                            " <style type='css_text.css'>"
                            " </head>"
                            " <body>"
                            " <h1>Sensor to ESP32 Web Server</h1><h2>Temperature:</h2> <h2 id=\"temp\">""</h2>\r\n"
                            " <h2>Humidity:</h2><h2 id=\"hum\">""</h2>\r\n"
                            " <script>\r\n"
                            " $(document).ready(function(){\r\n"
                            " setInterval(getData,1000);\r\n"
                            " function getData(){\r\n"
                            " $.ajax({\r\n"
                            "  type:\"GET\",\r\n"
                            "  url:\"data\",\r\n"
                            "  success: function(data){\r\n"
                            "  var s = data.split(\'-\');\r\n"
                            "  $('#temp').html(s[0]);\r\n"
                            "  $('#hum').html(s[1]);\r\n"
                            "}\r\n"
                            "}).done(function() {\r\n"
                            "  console.log('ok');\r\n"
                            "})\r\n"
                            "}\r\n"
                            "});"
                            "</script>\r\n"
                            "</body>";
